apiVersion: agents/v1
kind: Actuators
metadata:
  name: package-deployer-actuators
  labels:
    app: package-deployer-actuators
    type: autonomous
spec:
  mcp-servers:
    kubernetes:
      type: streamable-http
      url: http://kubernetes-mcp-server:8081/mcp
      sse_read_timeout: 30
    mcp-time:
      type: stdio
      args: []
      command: /app/actions/mcp/servers/time/mcp-time
  builtin-functions:
  - helm-template
  - helm-upgrade
  - helm-list-releases
  - helm-get-history
  - helm-get-values
  - helm-rollback
  - helm-uninstall
  - helm-test
  - kubernetes-list-workloads
  - kubernetes-get-namespace-events
  exclude-tools:
  - kubernetes-configuration_view
  - kubernetes-events_list
  - kubernetes-namespaces_list
  - kubernetes-nodes_stats_summary
  - kubernetes-configuration_contexts_list
