version: '3.9'

x-serving-args: 
  HOST_SERVING_MODEL_PATH: &host_serving_model_path ${HOST_SERVING_MODEL_PATH:-./agent/serving/triton/models/qwen2.5-tensorrtllm}
  SERVICE_MODEL_PATH: &serving_model_path ${SERVICE_MODEL_PATH:-/models/qwen2.5-tensorrtllm}
  HOST_MODEL_CKPT: &host_model_ckpt ${HOST_MODEL_CKPT:-/root/workspace/lnd/aiops/vlm/Qwen/Qwen2.5-7B-Instruct}
  MODEL_CKPT: &model_ckpt ${MODEL_CKPT:-/app/tensorrt_llm/models/Qwen2.5-7B-Instruct}

x-triton-backend-env: &triton-python-backend-env
  MODEL_PATH: /root/artifacts/Qwen/Qwen2.5-7B-Instruct
  QUANTIZATION_TYPE: ${QUANTIZATION_TYPE}
  ATTENTION_IMPL: flash_attention_2
  MAX_HISTORY: 5
  MAX_NEW_TOKENS: 512
  TEMPERATURE: 0.7
  TOP_P: 0.9
  NVIDIA_VISIBLE_DEVICES: all
  NVIDIA_DRIVER_CAPABILITIES: compute,utility

x-gpu-resources: &gpu-resources
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

x-common-agent-env: &common-agent-env
  OCI_REGISTRY_SECRET: /run/secrets/oci-registry
  KAFKA_BOOTSTRAP_SERVERS: kafka-server:9092
  KUBECONFIG: /run/secrets/kubernetes-config
  AGENT_MODE: ${AGENT_MODE:-dev} # eval, prod, dev
  INFERENCE_SERVER_TYPE: ${INFERENCE_SERVER_TYPE:-tensorrt-llm}

x-prometheus-env: &prometheus-env
  PROMETHEUS_URL: ${PROMETHEUS_URL}

secrets:
  oci-registry:
    file: ./.secrets/oci-registry
  kubernetes-config:
    file: ~/.kube/config


services:
  # LLM 
  ## Development Server for TensorRT-LLM
  main-tensorrt-llm-server:
    profiles: ["serving", "serving-tensorrt-llm"]
    image: nvcr.io/nvidia/tensorrt-llm/release:1.3.0rc5
    container_name: main-tensorrt-llm-server
    volumes:
    - source: *host_serving_model_path
      target: /app/tensorrt_llm/models/qwen3
      type: bind
    - /root/workspace/lnd/aiops/apps/newbie-app/agent/serving/optimization/tensorrt_llm:/app/tensorrt_llm/src/
    - source: *host_model_ckpt
      target: /app/tensorrt_llm/tokenizer
      type: bind
    command: 
    - /bin/bash
    - -c 
    - /app/tensorrt_llm/src/scripts/serve.sh
    ports:
      - "8001:8000"
    gpus: all
    <<: *gpu-resources
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - triton-ai-network

  main-vllm-server:
    profiles: ["serving", "serving-vllm"]
    image: nvcr.io/nvidia/vllm:26.03.post1-py3
    container_name: main-vllm-server
    volumes:
    - source: *host_model_ckpt
      target: /model
      type: bind
    environment:
      - VLLM_USE_V1=0
    command: >
      vllm serve /model
      --host 0.0.0.0
      --port 8000
      --dtype half
      --enforce-eager
      --gpu-memory-utilization 0.8
      --max-model-len 32768
      --language-model-only
    #--reasoning-parser qwen3
    ports:
      - "8001:8000"
    gpus: all
    <<: *gpu-resources
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - triton-ai-network

  ##  Production Server for TensorRT-LLM
  triton-server:
    profiles: ["serving"]
    build:
      context: ./agent/serving/triton/docker
      dockerfile: Dockerfile.triton
      args:
        BUILD_MODE: ${BUILD_MODE:-prod-tensorrt-llm}  # 'dev' or 'prod-py' or 'prod-tensorrt-llm'
      additional_contexts:
        site-packages: /root/miniconda3/envs/aiops-py312/lib/python3.12/site-packages
    image: triton-ai-server:${BUILD_MODE:-prod-tensorrt-llm}
    container_name: triton-ai-server
    ports:
      - "8000:8000"   # HTTP
      - "8001:8001"   # gRPC
      - "8002:8002"   # Metrics
    environment:
      <<: *triton-python-backend-env
    volumes:
      - source: *host_serving_model_path
        target: *serving_model_path
        type: bind
      - source: *host_model_ckpt
        target: *model_ckpt
        type: bind
      #- /root/workspace/lnd/aiops/vlm/Qwen/Qwen2.5-7B-Instruct:/root/artifacts/Qwen/Qwen2.5-7B-Instruct:ro
      #- ./agent/serving/triton/models/qwen3-vl:/models/qwen3-vl:ro # comment out this when running non-python deployments/
      #- ./agent/serving/triton/models/qwen2.5-tensorrtllm:/models/qwen2.5-tensorrtllm:ro
    #command: tritonserver --model-repository=/models --log-verbose=1
    command: sleep 6000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v2/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    gpus: all
    <<: *gpu-resources
    networks:
      - triton-ai-network

  # Agents
  deployer-agent:
    profiles: ["agent", "standard"]
    build:
      context: ./agent/
      dockerfile: ./Dockerfile.agents
      additional_contexts:
        templates: ./agent/templates
        actions: ./agent/actions
        memory: ./agent/memory
    image: agent-generic:latest
    container_name: deployer-agent
    secrets: 
    - oci-registry 
    - kubernetes-config
    environment: 
      <<: *common-agent-env
      PERSONA: deployer
    volumes:
    - ./agent/personas:/app/personas:rw
    - ./agent/qwen-ops-agent.py:/app/qwen-ops-agent.py:rw # for dev purposes only
    - ./agent/templates:/app/templates:rw
    - ./agent/actions/:/app/actions:rw
    - ./agent/memory/:/app/memory:rw
    - source: *host_model_ckpt
      target: /mnt/checkpoint
      type: bind
    - /root/.config/gcloud:/root/.config/gcloud:rw # for GKE auth, if needed
    command: >
      python -u qwen-ops-agent.py 
    networks:
      - triton-ai-network
    depends_on:
      kafka-server:
        condition: service_started
      # main-tensorrt-llm-server:
      #   condition: service_healthy
      kubernetes-mcp-server:
        condition: service_healthy
    restart: unless-stopped

  resiliency-optimizer-agent:
    profiles: ["agent", "standard"]
    image: agent-generic:latest
    container_name: resiliency-optimizer-agent
    secrets: 
    - oci-registry 
    - kubernetes-config
    environment: 
      PERSONA: resiliency-optimizer
      <<: 
      - *common-agent-env
      - *prometheus-env
    volumes:
    - ./agent/personas:/app/personas:rw
    - ./agent/qwen-ops-agent.py:/app/qwen-ops-agent.py:rw # for dev purposes only
    - ./agent/templates:/app/templates:rw
    - ./agent/actions/:/app/actions:rw
    - ./agent/memory/:/app/memory:rw
    - source: *host_model_ckpt
      target: /mnt/checkpoint
      type: bind
    command: >
      python -u qwen-ops-agent.py 
    networks:
      - triton-ai-network
    depends_on:
      kafka-server:
        condition: service_started
      # main-tensorrt-llm-server:
      #   condition: service_healthy
      kubernetes-mcp-server:
        condition: service_healthy
    restart: unless-stopped

  chat-agent:
    profiles: ["agent", "standard"]
    image: agent-generic:latest
    container_name: chat-agent
    secrets: 
    - oci-registry 
    - kubernetes-config
    environment: 
      PERSONA: chat
      <<: 
      - *common-agent-env
      - *prometheus-env
    volumes:
    - ./agent/personas:/app/personas:rw
    - ./agent/qwen-chat-agent.py:/app/qwen-chat-agent.py:rw # for dev purposes only
    - ./agent/templates:/app/templates:rw
    - ./agent/actions/:/app/actions:rw
    - ./agent/memory/:/app/memory:rw
    - source: *host_model_ckpt
      target: /mnt/checkpoint
      type: bind
    - /root/.config/gcloud:/root/.config/gcloud:rw # for GKE auth, if needed
    command: >
      python -u qwen-chat-agent.py 
    ports:
      - "8002:8002"
    networks:
      - triton-ai-network
    depends_on:
      kafka-server:
        condition: service_started
      # main-tensorrt-llm-server:
      #   condition: service_healthy
      kubernetes-mcp-server:
        condition: service_healthy

  prompt-optimizer-agent:
    profiles: ["agent", "standard"]
    image: agent-generic:latest
    container_name: prompt-optimizer-agent
    environment: 
      PERSONA: prompt-optimizer
      <<: *common-agent-env
    volumes:
    - ./agent/personas:/app/personas:rw
    - ./agent/qwen-ops-agent.py:/app/qwen-ops-agent.py:rw # for dev purposes only
    - ./agent/templates:/app/templates:rw
    - ./agent/actions/:/app/actions:rw
    - ./agent/memory/:/app/memory:rw
    - source: *host_model_ckpt
      target: /mnt/checkpoint
      type: bind
    command: >
      python -u qwen-ops-agent.py 
    networks:
      - triton-ai-network
    depends_on:
      kafka-server:
        condition: service_started
      kubernetes-mcp-server:
        condition: service_healthy
    restart: unless-stopped

  # MCP and other tools
  kubernetes-mcp-server:
    profiles: ["tools", "standard"]
    image: agent-generic:latest
    container_name: kubernetes-mcp-server
    secrets: 
    - kubernetes-config
    environment: 
      KUBECONFIG: /run/secrets/config
    volumes:
    - ./agent/personas:/app/personas:ro
    - ./agent/templates/llm/qwen.yaml:/app/templates/llm/qwen.yaml:ro
    command: >
     /app/actions/mcp/servers/kubernetes/kubernetes-mcp-server --port 8081 --kubeconfig /run/secrets/kubernetes-config 
    # command: >
    #   sleep 6000
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - triton-ai-network
    extra_hosts: 
      - "host.docker.internal:host-gateway"

  # Memory and State Managements
  ## Episodic
  kafka-init:
    image: apache/kafka:4.2.0
    container_name: kafka-init
    volumes: 
     - ./agent/memory/store/episodic/kafka/data:/tmp/kraft-combined-logs:rw
     - ./agent/memory/store/episodic/kafka/config:/opt/kafka/config:rw
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
    command: >
      bash -c "/opt/kafka/bin/kafka-storage.sh format --config /opt/kafka/config/broker.properties --cluster-id $(/opt/kafka/bin/kafka-storage.sh random-uuid) --ignore-formatted" 
    networks:
      - triton-ai-network

  kafka-server:
    profiles: ["tools", "standard"]
    image: apache/kafka:4.2.0
    container_name: kafka
    volumes: 
     - ./agent/memory/store/episodic/kafka/data:/tmp/kraft-combined-logs:rw
     - ./agent/memory/store/episodic/kafka/config:/opt/kafka/config:rw
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_HEAP_OPTS: ${KAFKA_HEAP_OPTS:- -Xms256M -Xmx384M}
    command: >
      bash -c "/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/broker.properties"
    # healthcheck:
    #   test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/9092"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s
    networks:
      - triton-ai-network
    deploy:
      resources:
        limits:
          memory: 1024M

  ## Memory Management
  redis:
    profiles: ["memory", "standard"]
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./agent/memory/store/redis/data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - triton-ai-network

  agent-memory-server-api:
    profiles: ["memory", "standard"]
    image: redislabs/agent-memory-server:latest
    container_name: agent-memory-server-api
    ports:
      - "8009:8000"
    # env_file:
    #   - path: .env
    #     required: false
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=8000
      - LONG_TERM_MEMORY=True
      - ENABLE_TOPIC_EXTRACTION=True
      - ENABLE_NER=True
      - DISABLE_AUTH=true # For local development only
    depends_on:
      - redis
    # volumes:
    #   - ./agent_memory_server:/app/agent_memory_server
    networks:
      - triton-ai-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  triton-ai-network:
    driver: bridge
