apiVersion: agents/v1
kind: Actuators
metadata:
  name: prompt-optimizer-actuators
  labels:
    app: prompt-optimizer-actuators
    type: autonomous
spec:
  mcp-servers: {}
  builtin-functions:
    - "prompt-optimization-retrieve-system-prompt"
    - "prompt-optimization-retrieve-workflows"
    - "prompt-optimization-retrieve-workflow-result"
  exclude-tools: []