# Kafka Event Listener Configuration
apiVersion: agents/v1
kind: Sensors
metadata:
  name: prompt-optimizer-sensors
  labels:
    app: prompt-optimizer-sensors
    type: autonomous
spec:
  - type: KafkaEventListener
    config_type: KafkaEventListenerConfig
    bootstrap_servers:
    - kafka-server:9092
    group_id: prompt-optimizer
    auto_offset_reset: earliest
    topics:
    - prompt-opt.*
