# Low level objectives that agents can reference to when planning. 
# Can be though of high-level scripts when performing actions. 
apiVersion: agents/v1
kind: Goal
metadata:
  name: package-deployer-playbook
  labels:
    app: package-deployer-playbook
    type: autonomous
spec:
  play: |