# Kafka Event Listener Configuration
apiVersion: agents/v1
kind: Sensors
metadata:
  name: chat-sensors
  labels:
    app: chat-sensors
    type: autonomous
spec:
  - type: KafkaEventListener
    config_type: KafkaEventListenerConfig
    bootstrap_servers:
    - kafka-server:9092
    group_id: chat
    auto_offset_reset: earliest
    topics:
    - topics.chat
