FROM python:3.12 as build-stage

COPY ./common-requirements.txt ./requirements.txt

RUN pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt && \
    rm -rf ./requirements.txt

FROM build-stage as production-stage
WORKDIR /app
COPY ./entrypoint.sh ./
COPY ./qwen-ops-agent.py ./qwen-ops-agent.py
COPY --from=templates ./ ./templates
COPY --from=actions ./ ./actions

# Install needed mcp servers
RUN uvx kubernetes-mcp-server@latest -h

EXPOSE 8081

ENTRYPOINT ["/app/entrypoint.sh"]