FROM python:3.12 AS build-stage

# Install prerequisites
RUN apt-get update && apt-get install -y \
    curl \
    tar \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Install Helm (latest release)
RUN curl -fsSL https://get.helm.sh/helm-v4.0.0-linux-amd64.tar.gz -o helm.tar.gz \
    && tar -zxvf helm.tar.gz \
    && mv linux-amd64/helm /usr/local/bin/helm \
    && rm -rf linux-amd64 helm.tar.gz

# Install kubectl (latest stable release)
RUN KUBECTL_VERSION="$(curl -L -s https://dl.k8s.io/release/stable.txt)" \
    && curl -fsSL "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl

# Verify installation
RUN helm version
RUN kubectl version --client



COPY ./common-requirements.txt ./requirements.txt

RUN pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt && \
    rm -rf ./requirements.txt

FROM build-stage AS production-stage
WORKDIR /app
COPY ./entrypoint.sh ./
COPY ./qwen-ops-agent.py ./qwen-ops-agent.py
COPY --from=templates ./ ./templates
COPY --from=actions ./ ./actions

# Install needed mcp servers
RUN uvx kubernetes-mcp-server@latest -h

ENTRYPOINT ["/app/entrypoint.sh"]