FROM python:3.12 AS build-stage

# Install prerequisites
RUN apt-get update && apt-get install -y \
    curl \
    tar \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Install Helm (latest release)
RUN curl -fsSL https://get.helm.sh/helm-v4.0.0-linux-amd64.tar.gz -o helm.tar.gz \
    && tar -zxvf helm.tar.gz \
    && mv linux-amd64/helm /usr/local/bin/helm \
    && rm -rf linux-amd64 helm.tar.gz

# Install kubectl (latest stable release)
RUN KUBECTL_VERSION="$(curl -L -s https://dl.k8s.io/release/stable.txt)" \
    && curl -fsSL "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl

# Verify installation
RUN helm version
RUN kubectl version --client


# GCLOUD Support
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release \
    curl

RUN echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" > /etc/apt/sources.list.d/google-cloud-sdk.list


RUN apt-get update \
    && apt-get install -y google-cloud-cli google-cloud-cli-gke-gcloud-auth-plugin


COPY ./common-requirements.txt ./requirements.txt

RUN pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt && \
    rm -rf ./requirements.txt


RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg&& \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt update && \
    apt install -y docker-ce-cli

FROM build-stage AS production-stage
WORKDIR /app
COPY ./entrypoint.sh ./
COPY ./qwen-ops-agent.py ./qwen-ops-agent.py
COPY --from=templates ./ ./templates
COPY --from=actions ./ ./actions
COPY --from=notifications ./ ./notifications
COPY --from=management ./ /management

# Install needed mcp servers

# RUN uvx kubernetes-mcp-server@latest -h

ENTRYPOINT ["/app/entrypoint.sh"]